# GitHub Actions 工作流 - macOS 自动打包
# 将此文件放置在 .github/workflows/build-mac.yml

name: Build macOS App

on:
  push:
    branches: [main, develop]
    tags: ["v*"]
  pull_request:
    branches: [main]
  workflow_dispatch: # 允许手动触发

jobs:
  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: 安装依赖
        run: pnpm install

      - name: 构建应用 (${{ matrix.arch }})
        run: pnpm run build:mac -- --${{ matrix.arch }}
        env:
          # 如果需要代码签名，添加以下环境变量
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: mac-app-${{ matrix.arch }}
          path: |
            dist/*.dmg
            dist/mac/*.app
          retention-days: 30

      - name: 创建发布 (仅标签推送)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
          draft: true
          prerelease: contains(github.ref, 'beta') || contains(github.ref, 'alpha')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 创建通用分发包
  create-universal-package:
    needs: build-mac
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 创建通用分发包
        run: |
          mkdir -p universal-package

          # 复制 DMG 文件
          find artifacts -name "*.dmg" -exec cp {} universal-package/ \;

          # 创建说明文件
          cat > universal-package/安装说明.txt << 'EOF'
          # 简繁转换工具 - macOS 版本

          ## 选择合适的版本：

          - **Intel Mac (x64)**：选择包含 "x64" 的 DMG 文件
          - **Apple Silicon Mac (arm64)**：选择包含 "arm64" 的 DMG 文件

          ## 安装步骤：

          1. 双击对应的 DMG 文件
          2. 将应用拖拽到 Applications 文件夹
          3. 首次运行时，可能需要在"系统偏好设置 > 安全性与隐私"中允许运行

          ## 系统要求：

          - macOS 10.15 (Catalina) 或更高版本
          - 至少 100MB 可用磁盘空间
          EOF

          # 创建 ZIP 包
          cd universal-package
          zip -r ../简繁转换工具-macOS-通用版.zip .
          cd ..

      - name: 上传通用分发包
        uses: actions/upload-artifact@v4
        with:
          name: mac-universal-package
          path: 简繁转换工具-macOS-通用版.zip
          retention-days: 90
